# Generated by Django 3.0.1 on 2020-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_vid',
            field=models.FileField(default='default.mp4', upload_to='vids'),
        ),
    ]
